# Generated by Django 3.1.2 on 2020-11-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingAddress1',
            new_name='billingAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingAddress1',
            new_name='shippingAddress',
        ),
        migrations.AlterField(
            model_name='order',
            name='billingPostcode',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taka Order Total'),
        ),
    ]
